version: "3.9"
services:
  dev:
    build:
      context: ./
      args:
        VARIANT: "8.0"
    image: dev-kuro4-dam
    container_name: dev-kuro4-dam
    volumes:
      - ${PROJECT_DIR}:/workspace:cached
    command: sleep infinity
  mongo:
    image: mongo:7.0.4
    container_name: mongo
    command: --replSet rs0 --oplogSize 128 --bind_ip_all
    volumes:
      - ${DEVCON_DIR}/mongo/db:/data/db
      - ${DEVCON_DIR}/mongo/init/config-replica.js:/config-replica.js
    env_file:
      - mongo/mongo.env
    healthcheck:
      test: mongosh config-replica.js
      interval: 10s
      start_period: 30s